### ISSUE TITLE
rules.tsのSpacingRuleの単体テストを追加する

### ISSUE THREAD

**Issue by bun913** [bun913/textlint-rule-aws-service-name#49]

**Comment by bun913** [comment]
最初に生成してもらった段階では結構失敗する

```
FAIL  specs/src/regularRule/rules.spec.ts
  ● SpacingRule › getMaybe › should return a RuleParam with noSpacePattern

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,7 +1,7 @@
      Object {
    -   "expected": "AmazonProduct",
    +   "expected": "Amazon Product",
        "options": Object {
          "wordBoundary": true,
        },
        "patterns": Array [
          "AmazonProduct",

      84 |         options: { wordBoundary: true },
      85 |       };
    > 86 |       expect(spacingRule.getMaybe()).toStrictEqual(rule);
         |                                      ^
      87 |     });
      88 |
      89 |     it("should return a RuleParam with spaceDelimitedPattern", () => {

      at Object.<anonymous> (specs/src/regularRule/rules.spec.ts:86:38)

  ● SpacingRule › getMaybe › should return a RuleParam with spaceDelimitedPattern

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Object {
    -   "expected": "AWS Product Name",
    +   "expected": "AWSProductName",
        "options": Object {
          "wordBoundary": true,
        },
        "patterns": Array [
    -     "AWS Product Name",
    +     "AWSProduct Name",
        ],
      }

       95 |         options: { wordBoundary: true },
       96 |       };
    >  97 |       expect(spacingRule.getMaybe()).toStrictEqual(rule);
          |                                      ^
       98 |     });
       99 |
      100 |     it("should return a RuleParam with both noSpacePattern and spaceDelimitedPattern", () => {

      at Object.<anonymous> (specs/src/regularRule/rules.spec.ts:97:38)

  ● SpacingRule › getMaybe › should return a RuleParam with both noSpacePattern and spaceDelimitedPattern

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 2

      Object {
    -   "expected": "Amazon AWS Product Name",
    +   "expected": "AmazonAWSProductName",
        "options": Object {
          "wordBoundary": true,
        },
        "patterns": Array [
    -     "AmazonAWSProductName",
    -     "Amazon AWS Product Name",
    +     "AmazonAWSProduct Name",
        ],
      }

      106 |         options: { wordBoundary: true },
      107 |       };
    > 108 |       expect(spacingRule.getMaybe()).toStrictEqual(rule);
          |                                      ^
      109 |     });
      110 |   });
      111 |

      at Object.<anonymous> (specs/src/regularRule/rules.spec.ts:108:38)

  ● SpacingRule › spaceDelimitedPattern › should return a string with pascal case delimited by space

    expect(received).toBe(expected) // Object.is equality

    Expected: "AWS Product Name"
    Received: "AWSProduct Name"

      122 |       const service = new AwsService("AWSProductName", "");
      123 |       const spacingRule = new SpacingRule(service);
    > 124 |       expect(spacingRule["spaceDelimitedPattern"]()).toBe("AWS Product Name");
          |                                                      ^
      125 |     });
      126 |   });
      127 | });

      at Object.<anonymous> (specs/src/regularRule/rules.spec.ts:124:54)

Test Suites: 1 failed, 5 passed, 6 total
Tests:       4 failed, 50 passed, 54 total
Snapshots:   0 total
Time:        1.518 s, estimated 2 s
Ran all test suites matching /specs\//i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bun913** [comment]
ということて一旦、一箇所ずつテストを見ていくことにしました。

土台を作ってくれただけで割と助かるので、一旦コメントアウトしてみます。

```
describe("SpacingRule", () => {
  describe("getMaybe", () => {
    it("should return null if there is no pattern", () => {
      const service = new AwsService("Product", "Amazon");
      const spacingRule = new SpacingRule(service);
      expect(spacingRule.getMaybe()).toBeNull();
    });

  //   it("should return a RuleParam with noSpacePattern", () => {
  //     const service = new AwsService("Amazon Product", "");
  //     const spacingRule = new SpacingRule(service);
  //     const rule: RuleParam = {
  //       expected: "AmazonProduct",
  //       patterns: ["AmazonProduct"],
  //       options: { wordBoundary: true },
  //     };
  //     expect(spacingRule.getMaybe()).toStrictEqual(rule);
  //   });

  //   it("should return a RuleParam with spaceDelimitedPattern", () => {
  //     const service = new AwsService("AWSProductName", "");
  //     const spacingRule = new SpacingRule(service);
  //     const rule: RuleParam = {
  //       expected: "AWS Product Name",
  //       patterns: ["AWS Product Name"],
  //       options: { wordBoundary: true },
  //     };
  //     expect(spacingRule.getMaybe()).toStrictEqual(rule);
  //   });

  //   it("should return a RuleParam with both noSpacePattern and spaceDelimitedPattern", () => {
  //     const service = new AwsService("AmazonAWSProductName", "");
  //     const spacingRule = new SpacingRule(service);
  //     const rule: RuleParam = {
  //       expected: "Amazon AWS Product Name",
  //       patterns: ["AmazonAWSProductName", "Amazon AWS Product Name"],
  //       options: { wordBoundary: true },
  //     };
  //     expect(spacingRule.getMaybe()).toStrictEqual(rule);
  //   });
  });

  // describe("noSpacePattern", () => {
  //   it("should return a string with blank removed", () => {
  //     const service = new AwsService("Amazon Product", "");
  //     const spacingRule = new SpacingRule(service);
  //     expect(spacingRule["noSpacePattern"]()).toBe("AmazonProduct");
  //   });
  // });

  // describe("spaceDelimitedPattern", () => {
  //   it("should return a string with pascal case delimited by space", () => {
  //     const service = new AwsService("AWSProductName", "");
  //     const spacingRule = new SpacingRule(service);
  //     expect(spacingRule["spaceDelimitedPattern"]()).toBe("AWS Product Name");
  //   });
  // });
});
```

**Comment by bun913** [comment]
この状態だとテストが通るので、次のitをみていくことにします

**Comment by bun913** [comment]
一方以下のテストは本来意図しないケースであるため、削除しました。

ここに関しては　if分岐だけを見れば確かに通りえるパターンに見えるのでAIがこのように書いてくるのもまぁ確かに理解できるなぁと思いました。（リファクタポイントを見つけてくれました）

```ts
    // これは削除
    it("should return a RuleParam with both noSpacePattern and spaceDelimitedPattern", () => {
      const service = new AwsService("ProductName", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      const rule: RuleParam = {
        expected: "Amazon AWS Product Name",
        patterns: ["AmazonAWSProductName", "Amazon AWS Product Name"],
        options: { wordBoundary: true },
      };
      expect(spacingRule.getMaybe()).toStrictEqual(rule);
    });
```

**Comment by bun913** [comment]
次にちょっとなるほどな〜と勉強になったのはこちらのテストケースです。

本来 noSpacePattern() はprivateなメソッドなのですが、以下のように無理やり関数を呼び出しています。

これは私が意図していないことでしたが、このような方法があるのかと感心しました。

ですが、今回はpublicメソッドだけテストしたかったので、この辺りのテストは消しました。

```ts
  // noSpacePatterはprivateなメソッド
  describe("noSpacePattern", () => {
    it("should return a string with blank removed", () => {
      const service = new AwsService("Amazon Product", "");
      const spacingRule = new SpacingRule(service);
      // 無理やり呼び出すテクニックに感心しました
      expect(spacingRule["noSpacePattern"]()).toBe("AmazonProduct");
    });
  });
```

**Comment by bun913** [comment]
やってみて思ったのは

- 今回のChatGPTさんは分岐や通りえるパターンを極力書き出してくれていた
- メソッドの内容や文脈に沿ったっぽいテストを書いてくれる
- 一方で私の指示が長すぎたのか、privateメソッドもテストを書いてこようとするなど指示ももう少し熟練が必要

などと感じました。

**Comment by bun913** [comment]
ここまで出来上がったものはこれ

```ts
describe("SpacingRule", () => {
  describe("getMaybe", () => {
    it("should return null if there is no pattern", () => {
      const service = new AwsService("Product", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      expect(spacingRule.getMaybe()).toBeNull();
    });

    it("should return a Excessive Space Name", () => {
      const service = new AwsService("ProductName", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      const rule: RuleParam = {
        expected: "ProductName",
        // 不要なスペースを入れたパターンが返却される
        patterns: ["Product Name"],
        options: { wordBoundary: true },
      };
      expect(spacingRule.getMaybe()).toStrictEqual(rule);
    });

    it("should return a space Deleted Name", () => {
      const service = new AwsService("Product Name", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      const rule: RuleParam = {
        expected: "Product Name",
        // スペースを削除したパターンが返却される
        patterns: ["ProductName"],
        options: { wordBoundary: true },
      };
      expect(spacingRule.getMaybe()).toStrictEqual(rule);
    });

    it("should return a RuleParam with both noSpacePattern and spaceDelimitedPattern", () => {
      const service = new AwsService("ProductName", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      const rule: RuleParam = {
        expected: "Amazon AWS Product Name",
        patterns: ["AmazonAWSProductName", "Amazon AWS Product Name"],
        options: { wordBoundary: true },
      };
      expect(spacingRule.getMaybe()).toStrictEqual(rule);
    });
  });

});
```

**Comment by bun913** [comment]
せっかくなので GitHub copliotでテストを書こうとするとどんな感じになるのか試してみました。

まず以下のようにテストを一つだけ書いた状態で消してみます。

```ts
describe("SpacingRule", () => {
  describe("getMaybe", () => {
    it("should return null if there is no pattern", () => {
      const service = new AwsService("Product", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      expect(spacingRule.getMaybe()).toBeNull();
    });
  });
});
```

**Comment by bun913** [comment]
こんな感じでコメントを追記してみます

<img width="765" alt="image" src="https://user-images.githubusercontent.com/73948280/228711397-69d1450a-0220-41ba-a585-48ff3620c683.png">

**Comment by bun913** [comment]
乗ってきたので、次のテストを書きます。

次は本来は `ProductName` というサービス名を`ProductName`のようにスペースを消してしまう誤りを検知するためのルールを作る関数をチェックします。

私が `write test with include` くらいまでコメントで指示を書こうとした段階で先ほどまでの結果とまだ書いていないテストパターンを察してコメントの提案をしてくれます。

<img width="912" alt="image" src="https://user-images.githubusercontent.com/73948280/228713885-9b49705a-6f4f-47f7-af92-ea92b86939e0.png">


やばいですね。（語彙力）

そして、またも `it` くらいまで書いてみるとそれっぽいタイトルを提案してくれます。

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/73948280/228714028-7c7e50c5-adac-496f-9944-edcb61f1364f.png">

この提案を tabキーで受け入れると、この時点ですぐに私が想像したままのテストを提案してくれました

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/73948280/228714126-a0d36943-2793-42e4-a1f3-9f2357e566bd.png">

やばくないですか？（語彙力）

これをtabで受け入れて、ちょっと余計な文字列を消してあげればテストの完成です。

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/73948280/228714244-787dfabd-1e4b-4166-9618-344e82cc9eef.png">

```ts
    // write test with includeSpacePattern like Amazon Elastic Compute Cloud
    it("should return missing space rule if there has includeSpacePattern", () => {
      const service = new AwsService("Elastic Compute Cloud", prefixAmazon);
      const spacingRule = new SpacingRule(service);
      const result = spacingRule.getMaybe();
      expect(result).toEqual({
        // ここのAmazonという文字列を消すだけの簡単なお仕事
        expected: "Elastic Compute Cloud",
        patterns: ["ElasticComputeCloud"],
        options: { wordBoundary: true },
      });
    });
```

**Comment by bun913** [comment]
とういことでここまでの流れを実際の動画で見ていきましょう。

間違いの修正も含めて30秒くらいでテストケースが作成できました。
![20230330_github_coplilot_test_flow](https://user-images.githubusercontent.com/73948280/228716337-f3d7a422-f1f2-4ecd-a4bb-9257cec71d11.gif)

**Comment by bun913** [comment]
まとめ

- ChatGPTにテストを一気に考えてもらって、自分で変更していくのもよし
- GitHub Copilotに必要な命令を与えて、一個ずつテストを書いてもらうのもよし
- はたまた両方を使っても良いかもです

いずれにしろ、意図した動作を書いてもらえる「プロンプト力」があれば、より素早くテストを書き終えることができそうですね。

ただサービスやコードの仕様を押さえて、提案されたコードが正しいかどうかを判断する力は依然として、いやむしろ今まで以上に必要なのかもしれないと思いました。
